from enum import Enum


class MicroAttackStage(Enum):
    INIT = 0

    TARGET_IDEN = 1
    SURFING = 2
    SOCIAL_ENGINEERING = 3
    HOST_DISC = 4
    SERVICE_DISC = 5
    VULN_DISC = 6
    INFO_DISC = 7

    USER_PRIV_ESC = 10
    ROOT_PRIV_ESC = 11
    NETWORK_SNIFFING = 12
    BRUTE_FORCE_CREDS = 13
    ACCT_MANIP = 14
    TRUSTED_ORG_EXP = 15
    PUBLIC_APP_EXP = 16
    REMOTE_SERVICE_EXP = 17
    SPEARPHISHING = 18
    SERVICE_SPECIFIC = 19
    DEFENSE_EVASION = 20
    COMMAND_AND_CONTROL = 21
    LATERAL_MOVEMENT = 22
    ARBITRARY_CODE_EXE = 23
    PRIV_ESC = 99

    END_POINT_DOS = 100
    NETWORK_DOS = 101
    SERVICE_STOP = 102
    RESOURCE_HIJACKING = 103
    DATA_DESTRUCTION = 104
    CONTENT_WIPE = 105
    DATA_ENCRYPTION = 106
    DEFACEMENT = 107
    DATA_MANIPULATION = 108
    DATA_EXFILTRATION = 109
    DATA_DELIVERY = 110
    PHISHING = 111

    # ATT&CK for ICS techniques
    # Initial Access (初始存取)
    DRIVE_BY_COMPROMISE = 200
    EXPLOIT_PUBLIC_FACING_APP_ICS = 201
    EXPLOITATION_OF_REMOTE_SERVICES_ICS = 202
    EXTERNAL_REMOTE_SERVICES = 203
    INTERNET_ACCESSIBLE_DEVICE = 204
    REMOTE_SERVICES_ICS = 205
    REPLICATION_THROUGH_REMOVABLE_MEDIA = 206
    ROGUE_MASTER = 207
    SPEARPHISHING_ATTACHMENT_ICS = 208
    SUPPLY_CHAIN_COMPROMISE = 209
    TRANSIENT_CYBER_ASSET = 210
    WIRELESS_COMPROMISE = 211
    
    # Execution (執行)
    AUTORUN_IMAGE = 212
    CHANGE_OPERATING_MODE = 213  # T0858
    COMMAND_LINE_INTERFACE_ICS = 214
    EXECUTION_THROUGH_API = 215
    GRAPHICAL_USER_INTERFACE = 216
    HOOKING_ICS = 217
    MODIFY_CONTROLLER_TASKING = 218  # T0821
    NATIVE_API_ICS = 219
    SCRIPTING_ICS = 220
    USER_EXECUTION_ICS = 221
    
    # Persistence (持續性)
    HARDCODED_CREDENTIALS = 222
    MODIFY_PROGRAM = 223
    MODULE_FIRMWARE = 224
    PROJECT_FILE_INFECTION = 225
    SYSTEM_FIRMWARE = 226
    VALID_ACCOUNTS_ICS = 227
    
    # Privilege Escalation (權限提升)
    EXPLOITATION_FOR_PRIVILEGE_ESCALATION = 228
    # HOOKING_ICS already defined above
    
    # Evasion (規避)
    # CHANGE_OPERATING_MODE already defined above
    EXPLOITATION_FOR_EVASION = 229
    INDICATOR_REMOVAL_ON_HOST_ICS = 230
    MASQUERADING_ICS = 231
    ROOTKIT_ICS = 232
    SPOOF_REPORTING_MESSAGE = 233
    SYSTEM_BINARY_PROXY_EXECUTION = 234
    
    # Discovery (探索)
    NETWORK_CONNECTION_ENUMERATION = 235
    NETWORK_SNIFFING_ICS = 236
    REMOTE_SYSTEM_DISCOVERY_ICS = 237
    REMOTE_SYSTEM_INFORMATION_DISCOVERY = 238
    WIRELESS_SNIFFING = 239
    
    # Lateral Movement (橫向移動)
    DEFAULT_CREDENTIALS = 240
    # EXPLOITATION_OF_REMOTE_SERVICES_ICS already defined
    # HARDCODED_CREDENTIALS already defined
    LATERAL_TOOL_TRANSFER = 241
    PROGRAM_DOWNLOAD = 242  # T0843
    # REMOTE_SERVICES_ICS already defined
    # VALID_ACCOUNTS_ICS already defined
    
    # Collection (收集)
    ADVERSARY_IN_THE_MIDDLE_ICS = 243
    AUTOMATED_COLLECTION_ICS = 244
    DATA_FROM_INFORMATION_REPOSITORIES_ICS = 245
    DATA_FROM_LOCAL_SYSTEM_ICS = 246
    DETECT_OPERATING_MODE = 247
    IO_IMAGE = 248
    MONITOR_PROCESS_STATE = 249
    POINT_AND_TAG_IDENTIFICATION = 250  # T0861
    PROGRAM_UPLOAD = 251  # T0845
    SCREEN_CAPTURE_ICS = 252
    # WIRELESS_SNIFFING already defined
    
    # Command and Control (命令與控制)
    COMMONLY_USED_PORT = 253
    CONNECTION_PROXY = 254
    STANDARD_APPLICATION_LAYER_PROTOCOL = 255
    
    # Inhibit Response Function (抑制響應功能)
    ACTIVATE_FIRMWARE_UPDATE_MODE = 256
    ALARM_SUPPRESSION = 257
    BLOCK_COMMAND_MESSAGE = 258
    BLOCK_REPORTING_MESSAGE = 259
    BLOCK_SERIAL_COM = 260
    CHANGE_CREDENTIAL = 261
    DATA_DESTRUCTION_ICS = 262
    DENIAL_OF_SERVICE_ICS = 263
    DEVICE_RESTART_SHUTDOWN = 264
    MANIPULATE_IO_IMAGE = 265
    MODIFY_ALARM_SETTINGS = 266
    # ROOTKIT_ICS already defined
    SERVICE_STOP_ICS = 267
    # SYSTEM_FIRMWARE already defined
    
    # Impair Process Control (損害程序控制)
    BRUTE_FORCE_IO = 268
    MODIFY_PARAMETERS = 269  # T0836
    # MODULE_FIRMWARE already defined
    # SPOOF_REPORTING_MESSAGE already defined
    UNAUTHORIZED_COMMAND_MESSAGE = 270
    
    # Impact (影響)
    DAMAGE_TO_PROPERTY = 271
    DENIAL_OF_CONTROL = 272
    DENIAL_OF_VIEW = 273
    LOSS_OF_AVAILABILITY = 274
    LOSS_OF_CONTROL = 275
    LOSS_OF_PRODUCTIVITY_AND_REVENUE = 276
    LOSS_OF_PROTECTION = 277
    LOSS_OF_SAFETY = 278
    LOSS_OF_VIEW = 279
    MANIPULATION_OF_CONTROL = 280
    MANIPULATION_OF_VIEW = 281
    THEFT_OF_OPERATIONAL_INFORMATION = 282

    NON_MALICIOUS = 999


class MacroAttackStage(Enum):
    NONE = 0
    PASSIVE_RECON = 1
    ACTIVE_RECON = 2
    PRIVLEDGE_ESC = 3
    ENSURE_ACCESS = 4
    TARGETED_EXP = 5
    ZERO_DAY = 6
    DISRUPT = 7
    DISTROY = 8
    DISTORT = 9
    DISCLOSURE = 10
    DELIVERY = 11
